// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKxsPm4xNWyx5ag2Z4UvsUgl9VkXau3g',
    appId: '1:264168242614:web:8a343e4f1fa4b8c6375517',
    messagingSenderId: '264168242614',
    projectId: 'autoworld222222000333',
    authDomain: 'autoworld222222000333.firebaseapp.com',
    databaseURL: 'https://autoworld222222000333-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoworld222222000333.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3qTUmoOW14gky-FIZj5dop4qgXKjBCU',
    appId: '1:264168242614:android:51fd4d7b748a78da375517',
    messagingSenderId: '264168242614',
    projectId: 'autoworld222222000333',
    databaseURL: 'https://autoworld222222000333-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoworld222222000333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRhAuWsInN_Ug5yaepUbMzmSqlC9EtR0',
    appId: '1:264168242614:ios:6cd8babbc72c1ef2375517',
    messagingSenderId: '264168242614',
    projectId: 'autoworld222222000333',
    databaseURL: 'https://autoworld222222000333-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoworld222222000333.appspot.com',
    iosClientId: '264168242614-fjq1c5emd2rduihgmmmlcbtrrcb3uq83.apps.googleusercontent.com',
    iosBundleId: 'com.AutoWorld.AutoWorldQa',
  );
}
